root: true
env:
  browser: true
  es2021: true
  node: true
  mocha: true

extends:
#  - airbnb-typescript
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier

parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: 'tsconfig.json'

plugins:
  - '@typescript-eslint'
  - "import"

rules:
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'

ignorePatterns:
  - 'static/**/*.js'
  - 'knexfile.js'
  - 'webpack.config.js'

overrides:
  - files:
      - 'tests/*.ts'
    rules:
      no-unused-vars: ['warn']
      '@typescript-eslint/no-unused-vars': 0
      '@typescript-eslint/no-unused-expressions': 'off'
