env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  mocha: true

extends:
  - eslint:recommended
  - plugin:node/recommended
  - airbnb-base
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"
  - mocha-no-only

parserOptions:
  ecmaVersion: 12
  "@typescript-eslint/no-empty-function": "off"
  "@typescript-eslint/no-var-requires": "off"

rules:
  no-underscore-dangle: "off"
  no-unused-vars: "off"
  no-inner-declarations: "off"
  no-console: "off"
  camelcase: "warn"
  no-param-reassign: "warn"
  func-names: "warn"
  max-len: "warn"
  no-restricted-syntax: "warn"
  guard-for-in: "warn"
  eqeqeq: "warn"
  indent: 
    - "error"
    - 2
    - MemberExpression: "off"
  node/no-unpublished-require: "off"

ignorePatterns:
  - "static/**/*.js"

overrides:
  - files:
      - "tests/*.js"
    rules:
      no-unused-expressions: "off"
