env:
  browser: true
  commonjs: true
  es2020: true
  node: true
  mocha: true

extends:
  - eslint:recommended
  - plugin:node/recommended
  - airbnb-base

parserOptions:
  ecmaVersion: 11

# plugins:

rules:
  node/no-unpublished-require: "off"

ignorePatterns:
  - "static/**/*.js"

overrides:
  - files:
      - "tests/*.js"
    rules:
      no-unused-expressions: "off"
