root: true
env:
  browser: true
  es2021: true
  node: true
  mocha: true

extends:
  - plugin:@typescript-eslint/recommended
  - prettier

parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: 'tsconfig.json'

plugins:
  - '@typescript-eslint'

rules:
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'

ignorePatterns:
  - "static/**/*.js"

overrides:
  - files:
    - "tests/*.js"
